# Generated by Django 3.2.9 on 2021-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('cover', models.CharField(max_length=500)),
                ('genre', models.CharField(blank=True, choices=[(1, 'Fantasy'), (2, 'Action'), (3, 'Adventure'), (4, 'Drama'), (5, 'Horror'), (6, 'Sci-Fi'), (7, 'Thriller'), (8, 'Biography'), (9, 'Comedy'), (10, 'Crime'), (10, 'History')], max_length=15)),
            ],
        ),
    ]
