# Generated by Django 3.2.9 on 2021-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, choices=[(1, 'SCI-FI'), (2, 'HORROR'), (3, 'ACTION'), (4, 'DRAMA'), (5, 'COMEDY'), (6, 'DOCUMENTARY'), (7, 'THRILLER')], max_length=15)),
            ],
        ),
    ]
