# Generated by Django 3.2.9 on 2021-11-30 09:01

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_watchlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('full_size', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='full-size/')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.coverimages'),
        ),
    ]
