# Generated by Django 3.2.9 on 2021-11-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211130_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover',
        ),
    ]
