# Generated by Django 3.2.9 on 2021-11-22 11:26

from django.db import migrations


def populate_database(apps, schema_editor):
    User = apps.get_model('users', 'User')

    User.objects.create(
        username='pera@test.com',
        password='pw123',
        first_name='Pera',
        last_name='Peric',
        email='pera@test.com',
        is_staff=False)

    User.objects.create(
        username='mika@test.com',
        password='pw123',
        first_name='Mika',
        last_name='Mikic',
        email='mika@test.com',
        is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
